# Generated by Django 4.1.4 on 2023-08-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('COSTUMER', 'costumer'), ('ADMIN', 'admin')], max_length=10),
        ),
    ]
