# Generated by Django 3.2.8 on 2023-08-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bakerytype'),
        ),
    ]
