# Generated by Django 4.1.4 on 2023-08-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230813_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumerprofile',
            name='phone',
        ),
    ]
